### ISSUE TITLE
Preselected Discrepancy Note Type is different in repeating groups

### ISSUE THREAD

**Issue by oba-reliatec** [reliatec-gmbh/LibreClinica#343] opened 2022-08-02 11:40 UTC
**Description:**
When creating a discrepancy note LibreClinica preselects the type most likely appropriate in the current context (usually *Annotation*, *Query* when logged in as monitor, *Failed Validation Check* when generated by a rule). However, when an item is member of a repeating group, *Failed Validation Check* is preselected while *Annotation* would be expected.

**Requirements:**
Study with a CRF containing at least one ungrouped item A, one item B in a non-repeating group, and one C in a repeating group.

**Steps to follow:**
1. login as data entry user
1. open the CRF in DataEntry mode
1. click on the flag next to item C to create a discrepancy note
1. in the pop-up window watch the preselected type of the discrepancy note

**Expected result:**
*Annotation*  
The preselected type should be independent of whether the item is in a repeating group or not.

**Actual result:**
*Failed Validation Check*

**Server Setup (optional):**
 - reproduced on Linux and Windows
 - Application Server Tomcat-9

**Additional context (optional):**
In Note.jsp the preselected type is read out of `<c:set var="typeId1" value="${discrepancyNote.discrepancyNoteTypeId}"/>`

**Comment by toskrip** [comment] 2024-09-24 09:14
I can reproduce it and I did have a look in the code, however there are more factors to consider. I would prefer to discuss it so that we can define how we want this issue to be resolved.

1. I can confirm that there is difference in application logic when it comes to creation of discrepancy notes in repeating groups compared to normal un-grouped items. Specifically the new discrepancy on grouped item is always opening the view with `monitor=1` query parameter.  This is true also when you have the eCRF opened in edit mode. There may be a reason for this, I would recommend to not change this unless we understand the reason behind.
2. Based on user role, the list of discrepancy type is dynamically created when the new discrepancy view is triggered. For your scenario (data entry/ investigator) allowed are `Failed Validation Check, Annotation, Reason for Change`. `Query` type is explicitly removed (which sounds OK, this user types should not be allowed create query discrepancy).
3. Here comes the inconsistency/ bug. Because of the view is opening in monitoring mode and not data entry mode, the pre-selected discrepancy note type is set to `Query`. But Query is not allowed option (for data entry) so the combo box defaults to the first item that is `Failed Validation Check` (this is the behaviour you see).

This means that for monitor user, the issue that you are describing is not happening because there conditions work well (`Query` is allowed and preset as well).

For data entry/investigator user I would suggest to preset the type to the `Annotation`. This is relatively easy fix where we do not change the original design that grouped item discrepancies are creating with  `monitor=1` query parameter (I have a feeling that there is a reason for this, just I do not see it currently). 

We have one more pull request on discrepancy notes opened now, which has a code clean up in it. When that one gets merged, I could prepare pull request for this if you agree with my solution.

**Comment by oba-reliatec** [comment] 2024-09-24 12:08
Thank you @toskrip for the careful investigation, description, and proposal for solution. Presetting the type to *Annotation* is also good because it is the most general type.

Removing the `monitor=1` should be tried anyway (maybe it is just a simple bug in the query), however I suggest to do this timely close to a more thorough overall testing, e.g. before a release (in case it is not).

**Comment by toskrip** [comment] 2024-09-24 12:38
I think there is more in it then removing `monitor=1`. When I see the query params for discrepancy note view and compared to non-grouped items in edit mode, there are different parameters coming to consideration. 

E.g. `enterData=1` is used but also it seems to consider the completion status of form to force reason for change with `isRfc=1` for non-grouped items. 

On the other hand repeating grouped items are using further query params that are not present for non-grouped items (`rowCount, isGroup, groupLabel, isLocked, eventName, eventDate, crfName`).

This all seems to be important in whole data entry decision workflow and I would prefer to first document for developers how the data entry workflow is controlled with query params before we start doing any changes there.

**Closed** 2024-09-24 15:23 UTC
Labels: bug
