### ISSUE TITLE
[BUG] - Discrepancy cannot be added to empty fields

### ISSUE THREAD

**Issue by j-bley** [reliatec-gmbh/LibreClinica#404] opened 2024-07-31 11:59 UTC
**Description:**
When trying to add a descrepancy note to an empty field, the note is not saved and the flag symbol is reset to the default blue one.

**Requirements:**
Reproduced in LibreClinica Version 1.0.0, 1.1.0 and 1.2.1

CRF in ‘Data entry started’ status with more than one tab, where at least one tab contains no data and has not yet been saved.

**Steps to follow:**
1. open CRF
2. open tab without data (not saved)
3. click flag to add discrepancy note
4. enter data for note and close window
5. color of flag is changed based an choosen discrepancy note
6. close CRF

**Expected result:**
Discrepancy note should be visible in tab

**Actual result:**
Discrepancy note is missing and flag has default blue color.

**Comment by toskrip** [comment] 2024-07-31 12:17
This is behaviour when the eCRF was opened for data entry first time, discrepancy created but eCRF with discrepancy was not saved (the exit was clicked now save). Such discrepancy cannot be assigned to item data because the item data record does not exist in database yet. After you added discrepancy you should see a message in discrepancy pop up:

ATTENTION: You must submit/save the form or CRF in the main window to add this note to the database. Otherwise your note will not be saved.

**Comment by j-bley** [comment] 2024-09-20 07:15
But this text in the pop-up is only shown when the user has the right to enter/change data.
When the user only has reading rights - for example as clinical monitor - the pop-up message is the following: Your Discrepancy note has been saved into database. This page will be closing automatically.

Which indicates that the note was saved, but that is not the case. 
And with only reading rights it is not possible for the user to save the crf itself.

**Comment by toskrip** [comment] 2024-09-20 10:52
You are right. I can reproduce it and this behaviour is not consistent from monitor user perspective so it is indeed a bug. 

As I mentioned before discrepancy needs to be associated with item data. When there is nothing entered in tab it does not get saved. If there is something entered in a tab but nothing entered for particular item, the empty item data gets created and discrepancy is associated with the freshly created empty item data. 

You would basically want empty item data creation on new discrepancy also when nothing was saved in eCRF tab yet. But this would mean monitor would be triggering creating of item data which is questionable.

I will have a detailed look into the code and let you know when there is any progress on this issue. One option would be not allowing monitor to create discrepancy for item in eCRF tab where data entry did not save the form yet (this I think we can detect and handle properly).

**Comment by toskrip** [comment] 2024-09-23 13:29
I have implementation that would display this message to monitor directly when opening the new discrepancy pop-up (when clicking on flag icon):

![Selection_001](https://github.com/user-attachments/assets/3c1536a3-789c-49e5-a537-b19de3f61f4f)

**Comment by oba-reliatec** [comment] 2024-09-24 11:43
I think @toskrip's solution is the best that can be done, given the architecture.

In practice it might well be, that a monitor wants to prompt an investigator to enter data in empty fields by means of a discrepancy note. But if this makes the monitor trigger the creation of (empty) data items, as @toskrip pointed out, this is questionable.
If I got it right, the behaviour applies only to empty tabs. So if there are single empty items in a saved tab, the monitor can attach notes to it. This alleviates the drawback.

**Comment by toskrip** [comment] 2024-09-24 12:21
Yes it is only issue in never saved tab. If tab/section was one time saved by data entry the empty item data is created by data entry at this point so monitor can normally attach discrepancies to those empty item data records.

**Closed** 2024-09-24 12:50 UTC
Labels: bug
