### ISSUE TITLE
Insert valid rule with ShowAction failing [BUG] 

### ISSUE THREAD

**Issue by AaronSquirrel** [reliatec-gmbh/LibreClinica#310] opened 2022-02-08 22:59 UTC
**Description:**
I am trying to test out LibreClinica by loading CRFs (.xls) and Rules (.xml) from my OpenClinica Community version (3.15.x). When I try to load valid rules xml files I keep getting an error ShowAction OID I_AZEGF_AZEGFR_PART6_6 is not Valid. I know for a fact that is a valid OID.

**Requirements:**
1. An event with a few question in the CRF with a hidden question.
2. Valid XML rule to show hidden question.

**Steps to follow:**
1. Login
2. Tasks -> Build Study -> + icon to add rule
3. Select valid rule .xml file by clicking "Chose File"
4. Click Continue

**Expected result:**
Rule should report added/updated.

**Actual result:**
ShowAction OID I_AZEGF_AZEGFR_PART6_6 is not Valid.

**Screenshots:**
The error along with the valid OID
![Screen Shot 2022-02-08 at 2 52 12 PM](https://user-images.githubusercontent.com/52079007/153089145-e6ef0c23-c3aa-43bb-a53b-030da9e0f2c1.png)

**Server Setup (optional):**
 - OS Ubuntu Linux 20.04
 - Application Server: tomcat9                              9.0.31-1ubuntu0.1
 - Java: openjdk-11-jre-headless:amd64        11.0.13+8-0ubuntu1~20.04
 - Postgresql: postgresql-11                        11.14-2.pgdg20.04+1

**Additional context:**
The XML I am trying to load for the rule. 
<!--
Version 0.1 - Redo to try this in LC
VARIABLES:
Study Event OID: SE_EGFRMUTATIONSANDTKIS
CRF Veriosn OID: F_AZEGFR_PART6_01
      Group OID: IG_AZEGF_UNGROUPED_3017 

 Item Target OID: I_AZEGF_AZEGFR_PART6_5 = 1 or 2 or 3 or 4 or 5 or 6 
Item OID to Show:  I_AZEGF_AZEGFR_PART6_6

Notes: 
Could not get the XML to show up so using screen shot of the XML here:
![Screen Shot 2022-02-08 at 3 05 38 PM](https://user-images.githubusercontent.com/52079007/153090656-9c5ca7e2-edce-46ec-8ee6-805c589dd6b3.png)

**Comment by toskrip** [comment] 2022-02-09 19:26
just to confirm, the screenshot with item metadata showing the item group IG_AZEGF_UNGROUPED_3017 is from your LibreClinica system? I am asking because these _number item groups are usually created based on not unique item group names (they get this generated suffix). This can complicates rule transfers because your original OC system may have actually different item group OIDs then item groups in LibreClinica.

If you could provide simple CRF with simple rule showing the problem it would help us to replicate the issue.

**Comment by AaronSquirrel** [comment] 2022-02-09 20:56
Thank you for the quick response. I can assure you that IG_AZEGF_UNGROUPED_3017 if definitally from the LibreClinica system Version: 1.1.0 - Changeset: 7ab59c39e732 2021-10-18 11:02 -0400. 

Attached is a simple CRF and rule to test this all out that does also error out. 
[test_CRF.xls](https://github.com/reliatec-gmbh/LibreClinica/files/8036141/test_CRF.xls)
I had to zip the XML to int could be uploaded. 
[LibreClinica_Test_Rule.xml.zip](https://github.com/reliatec-gmbh/LibreClinica/files/8036146/LibreClinica_Test_Rule.xml.zip)
Here is what this test case look like on our system:
![Screen Shot 2022-02-09 at 12 50 59 PM](https://user-images.githubusercontent.com/52079007/153288379-259931a0-63ef-4fd1-881b-267701b8aaca.png)
Details of the error screen:
<img width="1177" alt="Screen Shot 2022-02-09 at 12 47 49 PM" src="https://user-images.githubusercontent.com/52079007/153288416-6ab4c002-52de-417f-8148-c6f64e1c6b40.png">

Thank you again and do let me know if you need any further details.

**Comment by toskrip** [comment] 2022-02-10 11:45
Thanks for example. I was able to reproduce your problem. I will prepare a fix for this issue.

**Comment by toskrip** [comment] 2022-02-10 14:05
fix will be implemented in lc-rule-val branch

**Closed as completed** 2022-02-10 15:05 UTC
Labels: bug

**Comment by AaronSquirrel** [comment] 2022-02-11 00:24
Is there a nightly build of the LibreClinica-web war file from lc-develop that I might be able to snag and test out the bug fix? Else it look like the bug will be resolved in 1.2 when it comes out, I had hopped to do testing before then.
